-- 조회용 Oracle 테스트 DB 초기화 스크립트 (재실행 가능, 컨테이너 독립적).
-- 컨테이너 기동 후 SYSTEM 계정으로 적용한다 (README 참고):
--   docker exec -i <컨테이너명> sqlplus -s system/<SYSTEM비밀번호>@localhost:1521/FREEPDB1 < backend/sql/oracle-init.sql

SET DEFINE OFF

-- ===== 데이터 소유 계정 (없으면 생성) =====
BEGIN
  EXECUTE IMMEDIATE 'CREATE USER APP_USER IDENTIFIED BY "app_user_1234"';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -1920 THEN RAISE; END IF;  -- 이미 존재하면 무시
END;
/
GRANT CREATE SESSION, CREATE TABLE TO APP_USER;
ALTER USER APP_USER QUOTA UNLIMITED ON USERS;

-- 기존 테이블 정리 (재실행 대비)
BEGIN
  FOR t IN (SELECT table_name FROM all_tables
             WHERE owner = 'APP_USER' AND table_name IN ('BATCH_JOBS', 'CUSTOMERS', 'ORDERS')) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE APP_USER.' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

-- ===== 운영 데이터 스키마 (APP_USER 소유) =====

CREATE TABLE APP_USER.BATCH_JOBS (
  JOB_ID       VARCHAR2(30) PRIMARY KEY,
  JOB_NAME     VARCHAR2(100),
  STATUS       VARCHAR2(20),
  LAST_RUN_AT  DATE
);

CREATE TABLE APP_USER.CUSTOMERS (
  CUSTOMER_ID   VARCHAR2(20) PRIMARY KEY,
  CUSTOMER_NAME VARCHAR2(100),
  GRADE         VARCHAR2(20)
);

CREATE TABLE APP_USER.ORDERS (
  ORDER_ID     VARCHAR2(20) PRIMARY KEY,
  CUSTOMER_ID  VARCHAR2(20),
  STATUS       VARCHAR2(20),
  ORDER_DATE   DATE,
  AMOUNT       NUMBER(12)
);

-- ===== 샘플 데이터 =====

INSERT INTO APP_USER.BATCH_JOBS VALUES ('BATCH001', '일별 정산 배치', 'FAILED',  TO_DATE('2026-08-28 01:00', 'YYYY-MM-DD HH24:MI'));
INSERT INTO APP_USER.BATCH_JOBS VALUES ('BATCH002', '주문 집계 배치', 'SUCCESS', TO_DATE('2026-08-29 02:10', 'YYYY-MM-DD HH24:MI'));
INSERT INTO APP_USER.BATCH_JOBS VALUES ('BATCH003', '고객 등급 산정', 'RUNNING', TO_DATE('2026-08-29 03:00', 'YYYY-MM-DD HH24:MI'));

INSERT INTO APP_USER.CUSTOMERS VALUES ('C-1001', '홍길동', 'VIP');
INSERT INTO APP_USER.CUSTOMERS VALUES ('C-1002', '김철수', 'GOLD');
INSERT INTO APP_USER.CUSTOMERS VALUES ('C-1003', '이영희', 'SILVER');

INSERT INTO APP_USER.ORDERS VALUES ('O-777', 'C-1001', '배송중',   TO_DATE('2026-08-27', 'YYYY-MM-DD'), 128000);
INSERT INTO APP_USER.ORDERS VALUES ('O-778', 'C-1001', '결제완료', TO_DATE('2026-08-25', 'YYYY-MM-DD'),  45000);
INSERT INTO APP_USER.ORDERS VALUES ('O-779', 'C-1001', '배송완료', TO_DATE('2026-08-20', 'YYYY-MM-DD'), 233000);
INSERT INTO APP_USER.ORDERS VALUES ('O-801', 'C-1002', '배송완료', TO_DATE('2026-08-26', 'YYYY-MM-DD'),  71000);
INSERT INTO APP_USER.ORDERS VALUES ('O-802', 'C-1003', '주문접수', TO_DATE('2026-08-29', 'YYYY-MM-DD'),  19900);

COMMIT;

-- ===== agent 전용 조회 계정 (read-only) =====
-- agent는 이 계정으로만 접속한다. SELECT 권한만 부여하여 UPDATE/DELETE가 원천 차단된다.

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER VOC_READER IDENTIFIED BY "voc_reader_1234"';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -1920 THEN RAISE; END IF;  -- ORA-01920: 이미 존재하면 무시
END;
/

GRANT CREATE SESSION TO VOC_READER;

GRANT SELECT ON APP_USER.BATCH_JOBS TO VOC_READER;
GRANT SELECT ON APP_USER.CUSTOMERS  TO VOC_READER;
GRANT SELECT ON APP_USER.ORDERS     TO VOC_READER;

-- 등록된 쿼리가 스키마 접두사 없이 테이블명만으로 조회할 수 있도록 시노님 생성
CREATE OR REPLACE SYNONYM VOC_READER.BATCH_JOBS FOR APP_USER.BATCH_JOBS;
CREATE OR REPLACE SYNONYM VOC_READER.CUSTOMERS  FOR APP_USER.CUSTOMERS;
CREATE OR REPLACE SYNONYM VOC_READER.ORDERS     FOR APP_USER.ORDERS;

EXIT
